"""Initial schema

Revision ID: 4bb4ea1a490e
Revises: 
Create Date: 2026-07-28 11:23:14.357511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb4ea1a490e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('client_code', sa.String(length=50), nullable=True),
    sa.Column('boid_dpid', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pan')
    )
    op.create_table('ipos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('open_date', sa.DateTime(), nullable=True),
    sa.Column('close_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Open', 'Closed', 'Allotment_Announced', name='ipostatus'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('auto_detected', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('validated', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('registrars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('endpoint_type', sa.Enum('api', 'browser_automation', name='endpointtype'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('upload_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('valid_row_count', sa.Integer(), nullable=False),
    sa.Column('invalid_row_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('Queued', 'In_Progress', 'Completed', 'Failed', name='batchstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allotment_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('registrar_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Allotted', 'Not_Allotted', 'Website_Error', 'Invalid_PAN', 'Timeout', 'Server_Busy', name='resultstatus'), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('served_from_cache', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('cache_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batches.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ),
    sa.ForeignKeyConstraint(['registrar_id'], ['registrars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch_ipos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('success_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failure_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('timeout_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cache_hit_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('registrars_used', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_logs')
    op.drop_table('batch_ipos')
    op.drop_table('allotment_results')
    op.drop_table('upload_batches')
    op.drop_table('registrars')
    op.drop_table('ipos')
    op.drop_table('clients')
    # ### end Alembic commands ###
