"""Add Upcoming to IPOStatus

Revision ID: 93bad3ee7afa
Revises: caf9aa1ffe2a
Create Date: 2026-08-04 11:02:58.973524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '93bad3ee7afa'
down_revision: Union[str, Sequence[str], None] = 'caf9aa1ffe2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ipos', 'status',
               existing_type=mysql.ENUM('Open', 'Closed', 'Allotment_Announced'),
               type_=sa.Enum('Open', 'Upcoming', 'Closed', 'Allotment_Announced', name='ipostatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ipos', 'status',
               existing_type=sa.Enum('Open', 'Upcoming', 'Closed', 'Allotment_Announced', name='ipostatus'),
               type_=mysql.ENUM('Open', 'Closed', 'Allotment_Announced'),
               existing_nullable=False)
    # ### end Alembic commands ###
